print(True & True)
print(True & False)
print(False & False)
print("------------------")
print(True | True)
print(True | False)
print(False | False)
print("------------------")
print(True)
print(False) 